= Tmux-Demo (TechLunch - 20200227)

:nofooter:
:toc:
//:numbered:

== C'est quoi Tmux?

Tmux, tout comme Screen, est un multiplexeur de terminaux. C'est un outil permettant d'exploiter plusieurs terminaux au sein d'un seul et même affichage de terminal. Concrètement il s'agit de maintenir un terminal (une session) actif(ve) indépendamment de l'état de son affichage.

Cas d'usage typiques :
 - rendre persistant un processus pérenne
 - travailler en // sur plusieurs "écrans"
 - splitter son "écran" (indépendamment du client de Terminal (putty, terminator, etc.)

ALERT: il ne s'agit pas d'un nième utilitaire pour splitter l'écran du terminal... Le client de terminal sait le faire sans Tmux.

== Demo Time
=== Installation sur vos postes
Lancer les commandes Fedora qui vont bien pour en disposer en séance

=== Utilisation en local sur son laptop (Linux only)
. montrer la "survie" d'une session multiplexée
* Ouvrir un client de terminal localement
* 

=== Partageons quelques conventions de langage
La combinaison de touche CTRL+B qui permet d'exécuter les ordres Tmux (est le **prefixe**)
Tmux lance des **sessions**
On s'**atache** ou se **détache** d'une session
En status bar on observe l'existence de **fenêtres** (**windows**)
Si on split une fenêtre on parle de **panneaux** (**panes**)


== Et Screen alors ?

Screen est super simple mais :
- Pas de status bar par défaut
- Pas de fonctionnalité de split screen 

INFO: une fois qu'on maîtrise Tmux => screen c'est easy. L'inverse est moins vrai !
